#!/bin/bash
#used to spin up a quick calibre instance
#argument is 'lib_creator 'library you want to serve'
#requires xvfb imagemagick
#make sure to save books to the folder you're planning to create. 
lib_creator()
{
        clear
        mkdir -p /disks/c/to_add_/"$1"
        mkdir -p /disks/c/library/"$1"
        #Calibre and its server instance requires a book, or book-esque file (cbz, pdf, mobi, epub, etc) to validate the server instance.
        wget http://www.gutenberg.org/ebooks/1342.kindle.noimages -O /disks/c/to_add_/"$1"/pride.mobi
        xvfb-run calibredb add /disks/c/to_add_/"$1" --library-path /disks/c/library/"$1"
        echo "http://$(hostname -I)":8080| sed 's/ //g'
        calibre-server /disks/c/library/"$1"
        rm -rf /disks/c/to_add_/"$1"/*
}
